BentoBoxWorld/AOneBlock

src/main/java/world/bentobox/oneblock/listeners/BlockListener.java
The current implementation to allow "breaking" blocks completely overrides the vanilla block breaking behavior. This really surprised me when I tried OneBlock: you're not supposed to get iron ores from breaking the block with your bare hands! You need tools! 🤣
Anyway, so this PR fixes that, as well as potentially all the other issues that could occur later on: e.g. changes to the Unbreaking enchantment, use of the Fortune enchantment, any plugins that allows players to break blocks in unexpected ways (explosive pickaxes, automated "block breakers"...).
This, however, calls for a rewrite of the first phase. You can't get cobble out of breaking stone with your bare hands, you need tools for that.
You could also add an option, or even a permission, to allow players to have "super hands". I …
=> Made use of the vanilla block breaking behavior

pom.xml, src/main/java/world/bentobox/aoneblock/events/MagicBlockPhaseEvent.java, src/main/java/world/bentobox/aoneblock/listeners/BlockListener.java
After creating a Prestige addon for AOneBlock, it became apparent that you couldn't fetch the Old Phase (for comparison) through the API, as by the time the event is called, it has already been modified. 
I've simply stored this, and created a getter for manipulation, whilst trying to maintain your current codestyle.
=> Addition of getOldPhase to MagicBlockPhaseEvent

pom.xml, src/main/java/world/bentobox/aoneblock/commands/IslandPhasesCommand.java, src/main/java/world/bentobox/aoneblock/oneblocks/OneBlockObject.java, src/main/java/world/bentobox/aoneblock/oneblocks/OneBlockPhase.java, src/main/java/world/bentobox/aoneblock/oneblocks/OneBlocksManager.java, src/main/resources/phases/0_plains.yml
This PR Adds an (optional) "Icon" section to phase files, that allows you to *either* set a valid MC material (Not used in the phase at all) *or* add a Base64 Head icon.
=> Add "Icon" Section to Phase Config.

pom.xml, src/main/java/world/bentobox/aoneblock/AOneBlock.java, src/main/java/world/bentobox/aoneblock/dataobjects/OneBlockIslands.java, src/main/java/world/bentobox/aoneblock/listeners/BlockListener.java, src/main/java/world/bentobox/aoneblock/oneblocks/OneBlockPhase.java, src/main/java/world/bentobox/aoneblock/oneblocks/OneBlocksManager.java, src/main/resources/locales/en-US.yml, src/main/resources/phases/0_plains.yml
This Commit Adds Hologram Support (via HolographicDisplays) to Phases in the same way FixedBlocks work.
```yaml
holograms:
0: "&aGood Luck!"
1: "&aAnd Have Fun!"
```
This requires BentoBoxWorld/BentoBox#1794 for HolographicDisplays.
The other thing I will note is that due to the *first* block placed when the gamemode starts not being in any phase (Break 1 block to unlock plains) I've had to add the Starting hologram to the Locale file. It doesn't make very much sense, but thats the only good way I've found. I'm open to other suggestions though :)
```yaml
aoneblock:
island:
starting-hologram: "&aWelcome to AOneBlock\n&eBreak This Block to Begin"
```
=> Add Hologram Support to AOneBlock Phases

src/main/java/world/bentobox/aoneblock/Settings.java, src/main/resources/config.yml
The configuration file's comments contain multiple references to the
"/bsbadmin" command. This changes them to "/obadmin", the correct
command for AOneBlock.
=> Fix references to "/bsbadmin" in config

src/main/java/world/bentobox/aoneblock/AOneBlock.java, src/main/java/world/bentobox/aoneblock/commands/IslandPhasesCommand.java, src/main/java/world/bentobox/aoneblock/panels/PhasesPanel.java, src/main/resources/locales/en-US.yml, src/main/resources/panels/phases_panel.yml
This panel can allow viewing and change phase for players. 
Instead of a hard-codded panel that only displayed phases, users will be able to use this panel to customize it looks and change the current player phase.
Part of https://github.com/BentoBoxWorld/BentoBox/issues/1931
=> Implement user editable Phases Panel.

src/main/java/world/bentobox/aoneblock/listeners/HoloListener.java
There was an issue with an unnecessary check for an island at the hologram location. In all places, there already was an island object from which holograms must be removed. There is no necessity to search islands for all hologram locations and compare their island UUIDs. 
Fixes #243
=> Improve HoloListener performance

src/main/java/world/bentobox/aoneblock/AOneBlock.java, src/main/java/world/bentobox/aoneblock/commands/admin/AdminCommand.java, src/main/java/world/bentobox/aoneblock/commands/admin/AdminSanityCheck.java, src/main/java/world/bentobox/aoneblock/commands/admin/AdminSetChestCommand.java, src/main/java/world/bentobox/aoneblock/commands/admin/AdminSetCountCommand.java, src/main/java/world/bentobox/aoneblock/commands/island/IslandAboutCommand.java, src/main/java/world/bentobox/aoneblock/commands/island/IslandCountCommand.java, src/main/java/world/bentobox/aoneblock/commands/island/IslandPhasesCommand.java, src/main/java/world/bentobox/aoneblock/commands/island/IslandRespawnBlockCommand.java, src/main/java/world/bentobox/aoneblock/commands/island/IslandSetCountCommand.java, src/main/java/world/bentobox/aoneblock/commands/island/PlayerCommand.java, src/main/resources/addon.yml, src/main/resources/locales/en-US.yml
Adds a new command to users: `[player_cmd] respawnblock`.
This command allows respawning magic block in situations when it disappears. It is done by calling manually `BreakBlockEvent`. It may try to respawn entities, but in general, it should work.
It should be a good workaround for issues when the magic block disappears:
#238, #237, #156
=> Respawn command

src/main/java/world/bentobox/aoneblock/listeners/BlockListener.java
Rework how blocks are removed and replaced with water (if necessary).
This will remove blocks only if they are colliding with entity, and replace blocks with water, only if they collide or cannot be waterlogged.
=> Fixes #250

src/main/java/world/bentobox/aoneblock/AOneBlock.java, src/main/java/world/bentobox/aoneblock/PlaceholdersManager.java
`visited_island_lifetime_count` and `my_island_lifetime_count` placeholders.
Requested by #118, #195, #199
=> Implements 2 new placeholders

src/main/java/world/bentobox/aoneblock/dataobjects/OneBlockIslands.java, src/main/java/world/bentobox/aoneblock/oneblocks/OneBlockPhase.java
It was noticed that random blocks with rare chances were generating too freequently. 
I noticed that it calculated 2 different random values for block calculation, which increases the chance of a random block 2 times.
Also, the Next Oneblock Queue was incorrectly created. It used ArrayList which is the worst possible solution for it.
I switch it to Queue and LinkedList as it is exactly what is necessary for a block queue.
=> Fix random block issues

src/main/java/world/bentobox/aoneblock/listeners/BlockListener.java, src/main/java/world/bentobox/aoneblock/oneblocks/OneBlockCustomBlock.java, src/main/java/world/bentobox/aoneblock/oneblocks/OneBlockCustomBlockCreator.java, src/main/java/world/bentobox/aoneblock/oneblocks/OneBlockObject.java, src/main/java/world/bentobox/aoneblock/oneblocks/OneBlockPhase.java, src/main/java/world/bentobox/aoneblock/oneblocks/OneBlocksManager.java, src/main/java/world/bentobox/aoneblock/oneblocks/customblock/BlockDataCustomBlock.java
This adds an interface called `OneBlockCustomBlock` and a creator called `OneBlockCustomBlockCreator` that can be used by other addons to register custom blocks to the phases.
For the phase config, this adds a new approach to `blocks` with the example format
```yaml
blocks:
- type: data
data: minecraft:chest[waterlogged=true]
probability: 10
- type: data
data: minecraft:chest
probability: 10
- DIRT: 10 
```
The `data` type is a built-in custom block type. Developers can add more types to the creator and parse the map (an entry of the list) to their own custom block.
Also, `fixed-blocks` supports custom blocks, alongside with the current material name.
```yaml
fixedBlocks:
0:
type: data
data: minecraft:chest[waterlogged=true]
1: GRASS_BLOCK
2: GRASS_BLOCK
```
=> Custom Block support

src/main/java/world/bentobox/aoneblock/AOneBlock.java, src/main/java/world/bentobox/aoneblock/listeners/BlockListener.java, src/main/java/world/bentobox/aoneblock/listeners/HoloListener.java, src/test/java/world/bentobox/aoneblock/AOneBlockTest.java
This is a continuation of #306, but this time it uses the new `TextDisplay` API.
The addon will cache the `TextDisplay` for:
- Future use: Only create the new display if it does not exist.
- Marked deletion: Only delete the display related to the feature. There would be more displays from other plugins / addons, so we don't want to delete them just to update ours.
=> Improve hologram support

src/main/java/world/bentobox/aoneblock/oneblocks/OneBlockCustomBlockCreator.java, src/main/java/world/bentobox/aoneblock/oneblocks/OneBlocksManager.java, src/main/java/world/bentobox/aoneblock/oneblocks/customblock/BlockDataCustomBlock.java
This adds a check before Material to create `OneBlockCustomBlock` if the string is supported.
This enables developers to create their custom blocks from a single string (like #317), by creating their own `OneBlockCustomBlock` creator and register it as a "short creator".
=> Custom Block support as a string

src/main/java/world/bentobox/aoneblock/AOneBlock.java, src/main/java/world/bentobox/aoneblock/listeners/BlockListener.java
The PR to add support for ItemsAdder created two block listeners that ran concurrently. This PR fixes that and only makes one instance of the objects.
=> ItemsAdder fix

pom.xml, src/main/java/world/bentobox/aoneblock/listeners/BlockListener.java, src/main/java/world/bentobox/aoneblock/oneblocks/OneBlocksManager.java
This PR fixes the issue where the plugin will sometimes throws an error if ItemsAdder is installed because `ItemsAdder.getAllItems()` returns null. 
This PR also update the ItemsAdder API from 3.2.5 to 3.5.0b.
=> Fixed issue causing plugin to sometimes throw an error when ItemsAdder is installed.

src/main/java/world/bentobox/aoneblock/AOneBlock.java, src/main/java/world/bentobox/aoneblock/dataobjects/OneBlockIslands.java, src/main/java/world/bentobox/aoneblock/listeners/BlockListener.java, src/main/java/world/bentobox/aoneblock/listeners/CheckPhase.java, src/main/java/world/bentobox/aoneblock/listeners/MakeSpace.java, src/main/java/world/bentobox/aoneblock/oneblocks/OneBlockCustomBlock.java, src/main/java/world/bentobox/aoneblock/oneblocks/OneBlockCustomBlockCreator.java, src/main/java/world/bentobox/aoneblock/oneblocks/OneBlocksManager.java, src/main/java/world/bentobox/aoneblock/oneblocks/Requirement.java, src/main/java/world/bentobox/aoneblock/oneblocks/customblock/BlockDataCustomBlock.java, src/main/java/world/bentobox/aoneblock/oneblocks/customblock/MobCustomBlock.java, src/main/java/world/bentobox/aoneblock/panels/PhasesPanel.java, src/main/resources/locales/cs.yml, src/main/resources/locales/de.yml, src/main/resources/locales/en-US.yml, src/main/resources/locales/es.yml, src/main/resources/locales/fr.yml, src/main/resources/locales/hr.yml, src/main/resources/locales/hu.yml, src/main/resources/locales/ja.yml, src/main/resources/locales/pl.yml, src/main/resources/locales/ru.yml, src/main/resources/locales/tr.yml, src/main/resources/locales/vi.yml, src/main/resources/locales/zh-CN.yml, src/main/resources/locales/zh-TW.yml, src/main/resources/phases/0_plains.yml
Fixes:
- Everytime new phase was set, plugin sent the first block of the phase 2 times.
- CustomBlocks in fixedBlocks were causing issues where it was pushing the CustomBlock multiple times into queue.
- Phase config was not refreshed when doing /isa reload. I tested it and I do not see any issues.
Refactors:
- Variable naming refactors, because having name `obPhase` for `phase` instance + name `phase` for the `ConfigurationSection` was not really understandable (I changed it to `phaseConfig`)
Added features:
- New `CustomBlock` for mobs in format:
- `type: mob mob: ZOMBIE underlying-block: GRASS_BLOCK`  It will spawn a mob on top of underlying block. I know that mob spawns are not exactly counted as "destroyed block", but in this case it is needed. It would not make sense setting it in …
=> Bug fixes & CustomBlock type for mob spawning

src/main/java/world/bentobox/aoneblock/AOneBlock.java, src/main/java/world/bentobox/aoneblock/listeners/BlockListener.java, src/main/java/world/bentobox/aoneblock/oneblocks/OneBlockObject.java, src/main/java/world/bentobox/aoneblock/oneblocks/OneBlockPhase.java, src/main/java/world/bentobox/aoneblock/oneblocks/OneBlocksManager.java, src/main/java/world/bentobox/aoneblock/oneblocks/customblock/BlockDataCustomBlock.java, src/main/java/world/bentobox/aoneblock/oneblocks/customblock/ItemsAdderCustomBlock.java, src/main/java/world/bentobox/aoneblock/oneblocks/customblock/MobCustomBlock.java
This moved the ItemsAdder to a new `OneBlockCustomBlock`.
It bugs me that ItemsAdder is treated differently, although we already have `CustomBlock`. So this is to prove a point that something that supports ItemsAdder can be either a new `CustomBlock` or a new Addon.
P/S: Should I just remove the ItemsAdder code and create a new Addon, or just make a new `CustomBlock`?
=> Let ItemsAdder be a new OneBlockCustomBlock

src/main/java/world/bentobox/aoneblock/listeners/BlockListener.java
- Fixed `goToBlock` that was not working correctly after introducing `cooldown` requirement.
=> goToBlock fixes

src/main/java/world/bentobox/aoneblock/listeners/CheckPhase.java
If a minion broke the block at the end of the phase, the NPEs would occur as the newer code to check requirements and do placeholders was assuming a real player. This change protects that. Note that minions cannot be used to progress past a phase if there are any restrictions on the level change.
Fixes #389
=> Fix for null players, i.e., minions at end of phase.

pom.xml, src/main/java/world/bentobox/aoneblock/AOneBlock.java, src/main/java/world/bentobox/aoneblock/Settings.java, src/main/java/world/bentobox/aoneblock/commands/island/IslandBossBarCommand.java, src/main/java/world/bentobox/aoneblock/commands/island/PlayerCommand.java, src/main/java/world/bentobox/aoneblock/listeners/BossBarListener.java, src/main/resources/addon.yml, src/main/resources/locales/cs.yml, src/main/resources/locales/de.yml, src/main/resources/locales/en-US.yml, src/main/resources/locales/es.yml, src/main/resources/locales/fr.yml, src/main/resources/locales/hr.yml, src/main/resources/locales/hu.yml, src/main/resources/locales/id.yml, src/main/resources/locales/it.yml, src/main/resources/locales/ja.yml, src/main/resources/locales/pl.yml, src/main/resources/locales/pt.yml, src/main/resources/locales/ru.yml, src/main/resources/locales/tr.yml, src/main/resources/locales/uk.yml, src/main/resources/locales/vi.yml, src/main/resources/locales/zh-CN.yml, src/main/resources/locales/zh-TW.yml, src/main/resources/panels/phases_panel.yml
=> 420 boss bar

src/main/java/world/bentobox/aoneblock/listeners/BlockListener.java, src/main/java/world/bentobox/aoneblock/listeners/BossBarListener.java, src/main/resources/locales/en-US.yml
=> 426 boss bar improvements

src/main/java/world/bentobox/aoneblock/AOneBlock.java, src/main/java/world/bentobox/aoneblock/listeners/HoloListener.java, src/test/java/world/bentobox/aoneblock/listeners/HoloListenerTest.java
=> 436 hologram fails to delete
